### PR TITLE
Update geojs to 0.7.0

### PR DESCRIPTION
**Pull request by mgrauer**
@jbeezley @essamjoubori  or anyone else, PTAL.

To test this, especially if you haven't had a very recent master of Minerva, you'll need to ensure that

* your Girder is on version e61477c
* you have rebuilt the client (npm install)
* you kill your cherrypy server (python -m girder) and restart it (because we recently updated the mako template, and cherrypy needs to be recycled to serve the new template)

If that doesn't work, you can delete the girder/node_modules folder and the girder/plugins/minerva/node_modules folder then rerun npm install.  Expect to wait on this, and for many npm warnings.

Here's a screenshot from this branch showing 

* wms
* mongo
* geojson
* contour
* choropleth

datasets being rendered with the correct version of GeoJs.

screen shot 2016-02-13 at 3 54 01 pm

### CODE REVIEW

**Comment by kotfic** [comment]
@mgrauer LGTM

**Comment by aashish24** [comment]
@mgrauer I guess we won't be able to see the contour stuff in our local repo? But other than that LGTM :+1:

**Comment by mgrauer** [comment]
@aashish24 Not that contour file I screenshotted, but there is a [contour file in the repo](https://github.com/Kitware/minerva/blob/master/plugin_tests/data/expected_contour.json) (used for testing) that you could use to view in Minerva.

**Comment by aashish24** [comment]
Sure sounds good @mgrauer I won't be able to get it running in next few hours but will try it later. I would suggest let's merge it if CI looks good.

**Pull request merged**
