### PR TITLE
Transition to ESLint

### PR DESCRIPTION
**Pull request by danlamanna**
There's some issue with the Gruntfile being ignored I have to look into, other than that this is set.

### CODE REVIEW

**Comment by mgrauer** [comment]
@danlamanna 

How does updating underscore in Minerva play with the underscore version in Girder?

And can you explain how the new version of _ is pulled in?  I don't see any changes to the Gruntfile, and after blowing away node_modules in `girder` and `minerva` dirs, the `girder` node_modules _ version is 1.5.2.  When I check _.VERSION after rebuilding and serving this branch, my console reports 1.5.2.

**Comment by mgrauer** [comment]
Let me clarify what I did.

I had girder on `e61477c` and minerva on this branch.  Then I deleted `girder/node_modules` and `girder/plugins/minerva/node_modules` and ran `npm install` under `girder`.

**Comment by danlamanna** [comment]
I experienced the same clobbering so I reverted that dependency change - I must have not staged it to commit.

**Comment by jbeezley** [comment]
Updating underscore inside the local `package.json` will only make it available to the grunt scripts doing the build.  To provide a different underscore inside the runtime environment, you will need to override how girder builds its `girder.ext` bundle.

**Comment by mgrauer** [comment]
@danlamanna This looks generally sane.

Can you remove the underscore update and resolve merge commits, then I'll take a final QA pass?  Let me know if you run into merge trouble.

**Comment by danlamanna** [comment]
@mgrauer generally sane is what I was going for. Take a look :)

**Comment by mgrauer** [comment]
LGSTM.

Works on all my layers types, I can pop open an analysis panel, and I can re-order layers.

**Pull request merged**
