### PR TITLE
Add geoviz support

### PR DESCRIPTION
**Pull request by jbeezley**
This branch still contains a few changes necessary for the GeoViz plugin.
- Append authentication headers
- Add an event that is fired after the application starts
- Load extra javascript sources at load
- Override adapter method for a dataset

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley I fixed the server side tests but still having issues on client side testing.  I can push a fix, do you have any insight? 

Also, I local test this branch and it it looking ok, should we merge it after test fixes?

**Comment by aashish24** [comment]
thanks for the client side fixes @jbeezley. Is this ready to be merged or do we have some more work that needs to be done?

**Comment by jbeezley** [comment]
It's probably overdue to be merged.  We can make new PR's for further updates.

**Comment by aashish24** [comment]
> It's probably overdue to be merged. We can make new PR's for further updates.

Sounds good to me @jbeezley I have been doing local testing and other than some minor issues (which  can be taken care in next PR's) it LGTM 👍 Please go ahead and merge it. It looks good

**Pull request merged**
