### PR TITLE
[WIP] CSV Dataset

### PR DESCRIPTION
**Pull request by essamjoubori**
The end user will be able to upload and display csv data.

Using the dataset uploader:

screen shot 2016-02-01 at 2 29 27 pm

The csv data is saved in Girder as a file
screen shot 2016-02-01 at 2 29 57 pm

10 rows are saved in the metadata:
screen shot 2016-02-01 at 2 30 15 pm

The end user can view the csv file in a tabular format by clicking on the table icon in the dataset panel (in this step, the file is being retrieved from Girder and parsed with Papa parse):
screen shot 2016-02-01 at 2 30 39 pm

### CODE REVIEW

**Comment by mgrauer** [comment]
Thanks @essamjoubori .  I will take a look tomorrow.  

Then once we finish #257 and merge it, I'll help you get this one merged.

**Comment by aashish24** [comment]
@mgrauer since #257 is merged, can we get this one in master?

**Comment by mgrauer** [comment]
We'll need to rebuild this once #301 goes in.

**Comment by mgrauer** [comment]
Also will want to change `_isCsvFile` to be based off of mimetype, which we can get in the client through the file API.

**Comment by aashish24** [comment]
> We'll need to rebuild this once #301 goes in.

+1, 

> Also will want to change _isCsvFile to be based off of mimetype, which we can get in the client through the file API.

Sounds like a small change. If not, I would suggest we create an issue for it and merge this one post #301 merge

**Comment by mgrauer** [comment]
Yes, that would be a small change in addition to the CSV work, I wanted to track it here.

One other small change as a part of this, document 'csv' as a dataset_type in the docs.

**Comment by mgrauer** [comment]
This will *really* be going in with #312.  No, really.

**Pull request closed without merging**
