### PR TITLE
Minor tweaks ansible

### LINKED ISSUE #102: update ansible readme
The formatting is a bit off when displayed as RST in GitHub, specifically on the sections where commands are issued.  

https://github.com/Kitware/minerva/tree/2a2d6c7cc9ffa51ae1714b23ce7c9f6a6da1eeba/data_services/deploy/ansible

### PR DESCRIPTION
**Pull request by aashish24**
Fixes #102 #103 #104

### CODE REVIEW

**Comment by aashish24** [comment]
@mbertrand @mgrauer please review

**Comment by mgrauer** [comment]
I like the changes.  I'm going to reprovision a full VM before I approve, since we don't yet have automated tested for provisioning.

**Comment by mbertrand** [comment]
Looks good

**Comment by aashish24** [comment]
thanks @mbertrand. @mgrauer sure. Should we have a test for provisioning?

**Comment by mgrauer** [comment]
I'd love to have a test, but that may not be easy, and also will really bloat our overall Minerva build time.  I'm ok with requiring a rerun of the provisioning before any changes go in, as a stopgap until we figure out testing.

**Comment by mgrauer** [comment]
When I provisioned, there was a mismatch between the docs and the variable defined in the Vagrantfile, and I couldn't get it working unless I unified the Vagrantfile variable, and hosts, and README docs to all say "minerva_dataservices".

I've pushed a fix for this.

**Comment by aashish24** [comment]
Ah.. it must have created name dataservices vs minerva-dataservices. I thought about that but couldn't run it on this machine. Thanks for the name change. LGTM :+1:

**Pull request merged**
