### PR TITLE
[WIP] Tim demo new features

### PR DESCRIPTION
**Pull request by mgrauer**
I don't want to merge this, but will pull some fixes out of here.

### CODE REVIEW

**Comment by mgrauer** [comment]
I have pulled the mongo render fix out of this PR.

https://github.com/Kitware/minerva/pull/294

**Comment by mgrauer** [comment]
Other changes from here I'd like to merge, in the coming days.  I'll try to keep each of these in very small and easy to QA PRs so we don't have PRs hanging around.

 * update geojs to 0.7.0 
 * fix the wms legend
 * fix the layer movement in the layers panel
 * fix for datasets panel collapse/expand when layers order change (or a better fix than the temp one here)
  * csv widget
  * opacity addition for non-wms layers
  * change the response to a job success status event from re-rendering the entire dataset panel to adding a single dataset to the dataset collection

**Comment by aashish24** [comment]
@mgrauer why don't we close it and once you have it updated, you can open it again.

**Comment by mgrauer** [comment]
Finally got them all into PRs and issues.  Closing.

**Comment by aashish24** [comment]
Kudos @mgrauer :clap:

**Pull request closed without merging**
