### PR TITLE
Mongo render

### PR DESCRIPTION
**Pull request by mgrauer**
@mbertrand This should fix the mongo dataset rendering issue you saw.

It actually contains just two small commits, but I have merged #277 in because I anticipate that getting into master very soon.

Note that to use this branch you'll need to have girder on version e61477c, and then run `grunt init && grunt`.

Feel free to wait to QA until #277 goes in, and I can reform this branch then with the two commits plus a merge of master.

### CODE REVIEW

**Comment by mgrauer** [comment]
@mbertrand 

A simpler PR, PTAL.

Fixes the issue you saw where mongo datasets won't render.


screen shot 2016-02-12 at 4 29 23 pm

**Comment by mbertrand** [comment]
@mgrauer I can't load the page, getting the errors below, probably due to missing files (I ran npm install and grunt.  The tim_demo_new_features branch still works for me if I switch to that & run npm install/grunt.

404 on GET http://localhost:9000/static/built/plugins/minerva/buttons.dataTables.css 
404 on GET http://localhost:9000/static/built/plugins/minerva/jquery.dataTables.css 
404 GET http://localhost:9000/static/built/plugins/minerva/minerva.ext.min.js 
contourJsonReader.js:11Uncaught ReferenceError: geo is not defined(anonymous function) @ contourJsonReader.js:11
main.js:3Uncaught TypeError: minerva.App is not a function

**Comment by mgrauer** [comment]
@mbertrand 

Can you ensure that 

  * your Girder is on version e61477c 
  * you have re-fetched this branch and have the current history for it
  * you have rebuilt the client (as you say, npm install will do it)
  * you kill your cherrypy server (python -m girder) and restart it

and try again?

**Comment by mbertrand** [comment]
@mgrauer after completely removing node_modules directories from girder and minerva folders and rebuilding w/grunt, it worked!  LGTM.

**Comment by mgrauer** [comment]
Ah, good find, thanks.

**Pull request merged**
