### PR TITLE
Layers panel improvements

### PR DESCRIPTION
**Pull request by mgrauer**
@essamjoubori I pulled these from commits in #287  with a bit of slicing and dicing, and have given you authorship.

PTAL.

There are still some problems with the layer ordering (perhaps I didn't get the full fix?), but I'm ok with this going in for now.  I think we'll be fixing the layer/map ordering system in a larger refactor soon.  If you can find some small scale fixes to the layer ordering/movement I'd be ok with that.

### CODE REVIEW

**Comment by mgrauer** [comment]
Revised instructions:

This branch has a test failure, which should be easy to fix (remove a couple unused variables).  Can you take this over @essamjoubori ?  And if you have any further fixes to the layer ordering, please do them here.

**Comment by mgrauer** [comment]
@essamjoubori 

I merged master into this branch again cleanly, as it had a merge conflict.

Very recently, we have changed JS style checking and hinting to use eslint.  To run these tests locally, you'll probably need to do an npm install at the top level of girder, and be sure girder is on the right branch (look in the minerva docs).

**Comment by mgrauer** [comment]
> /home/travis/build/girder/plugins/minerva/web_external/js/views/body/LayersPanel.js
   41:13  error  "numberOfPossibleLayers" is defined but never used   no-unused-vars
   42:13  error  "numberOfLayersInSession" is defined but never used  no-unused-vars

**Comment by essamjoubori** [comment]
@mgrauer Fixed the failing tests and also fixed the bug with layers ordering. Do you want me to create a PR targeting master?

**Comment by mgrauer** [comment]
@essamjoubori 

Doesn't this PR target master?  It looks reasonable, I'll QA it.

**Comment by essamjoubori** [comment]
Oh yes it's already targeting master. Did notice that.

**Comment by mgrauer** [comment]
I can make this cause errors in some cases (e.g., load one layer, click down, or load two layers, click down on the top one), but it's good enough for now.  We'll be rewriting some of this when we do some refactoring, and I want to move on to the csv stuff.

Thanks for your help.  LGTM, merging.

**Pull request merged**
