### PR TITLE
[WIP] Postgres support

### PR DESCRIPTION
**Pull request by dorukozturk**
### 1) Download and import database to Postgresql
**Download the sample database**
```sh
wget https://midas3.kitware.com/midas/download/bitstream/458492/testdb.sql.gz
```
**Create the database to dump**
```sh
createdb -h localhost -p 5432 -U yourUserName -W --password minerva_db
```
This step will create a database named 'minerva_db' and  prompt you to enter your password. 

**Import the database to Postgresql**

```sh
gunzip -c testdb.sql.gz | psql minerva_db
```

### 2) Get minerva_db_items

**Clone Repository**
```sh
git clone https://github.com/OpenGeoscience/girder_db_items
```

**Checkout correct branch**

Repository | Branch
------------ | -------------
girder_db_items | geodata-endpoint

**Symlink plugin**
```sh
ln -sf "$(pwd)/girder_db_items" "$(pwd)/girder/plugins"
mv girder/plugins/girder_db_items girder/plugins/database_assetstore
```

**Pip install requirements for girder_db_items**
```sh
cd girder_db_items
pip install -r requirements.txt
```

### Install client code 
```sh
cd girder
npm install
```
### 3) Import database to Minerva

**Activate database_assetstore plugin**

selection_017

**Import database**

selection_019

**Fill out connection parameters**

selection_020

**Select the layers and number of features**

selection_021

### CODE REVIEW

**Comment by dorukozturk** [comment]
@aashish24 PTAL

**Comment by aashish24** [comment]
@dorukozturk is this branch is ready for review? I believe we had couple of issues. Let me know.

**Comment by dorukozturk** [comment]
@aashish24 I think there will be some changes on this branch. I will try to use this branch to leverage David's plugin and get Gryphon database up and running.

**Comment by aashish24** [comment]
> @aashish24 I think there will be some changes on this branch. I will try to use this branch to leverage David's plugin and get Gryphon database up and running.

+1

**Comment by aashish24** [comment]
@dorukozturk @matthewma7 is this branch still being worked on? Or do we have another branch for our postgres stuff?

**Comment by dorukozturk** [comment]
Actually this is the branch which adds the dialog to add a database assetstore from minerva as opposed to from girder. Which might make the user's life easier.

**Comment by matthewma7** [comment]
@aashish24, I have another https://github.com/Kitware/minerva/tree/postgres_geometry_link. but plannin

**Comment by matthewma7** [comment]
@aashish24, this https://github.com/Kitware/minerva/tree/postgres-geojson and https://github.com/Kitware/minerva/tree/postgres_geometry_link is what I am using. I planned to merge the later one back into the former at a certain point.

**Comment by aashish24** [comment]
Roger that @dorukozturk @matthewma7 so what I gathered that this branch and what @matthewma7 is working on has different features (complimentary) so we still need this one.

**Comment by dorukozturk** [comment]
@aashish24 Yes, that is correct. They are independent but complimentary. This will make the minerva user add a database assetstore as I pointed before.

**Comment by aashish24** [comment]
roger that @dorukozturk, thanks.

**Pull request closed without merging**
