### PR TITLE
Removed un-used / demo and experimental code

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@dorukozturk @jbeezley please review. There is one test failing (dataset) but it seems to be failing on th e master as well.

**Comment by jbeezley** [comment]
You have an import error:
```
133: Traceback (most recent call last):
133:   File "girder/utility/plugin_utilities.py", line 96, in loadPlugins
133:     plugin, root, appconf, apiRoot, curConfig=curConfig)
133:   File "girder/utility/plugin_utilities.py", line 224, in loadPlugin
133:     module = imp.load_module(moduleName, fp, pathname, description)
133:   File "/home/travis/build/girder/plugins/minerva/server/__init__.py", line 19, in <module>
133:     import loader
133:   File "/home/travis/build/girder/plugins/minerva/server/loader.py", line 28, in <module>
133:     from girder.plugins.minerva.rest import \
133:   File "/home/travis/build/girder/plugins/minerva/server/rest/analysis.py", line 29, in <module>
133:     from girder.plugins.minerva.rest.dataset import Dataset
133:   File "/home/travis/build/girder/plugins/minerva/server/rest/dataset.py", line 32, in <module>
133:     from girder.plugins.minerva.libs.carmen import get_resolver
```

Also, the dataset test is working fine on my branch.

**Comment by aashish24** [comment]
thanks @jbeezley I had some uncommitted changes. Should be able to push my changes soon with all the fixes.

**Comment by aashish24** [comment]
@jbeezley @dorukozturk all of the tests are passing now, this is ready for second review

**Comment by aashish24** [comment]
@jbeezley @dorukozturk okay if I merge this one in now?

**Comment by dorukozturk** [comment]
@aashish24 LGTM!

**Pull request merged**
