### PR TITLE
Centralize Girder version

### LINKED ISSUE #293: Make the girder version come from a single source
see #281

### PR DESCRIPTION
**Pull request by danlamanna**
Fixes #293 

@mgrauer If this approach is fine, I can use it for `romanesco_version` as well.

### CODE REVIEW

**Comment by mgrauer** [comment]
Go for it.

This looks great so far.

**Comment by aashish24** [comment]
Looks great @danlamanna

**Comment by mgrauer** [comment]
Good doc changes.  I'll test with a fresh ansible vm.

**Comment by mgrauer** [comment]
LGTMAA. merging.

AA == and ansible

**Pull request merged**
