### PR TITLE
Dataset info new layout

### PR DESCRIPTION
**Pull request by matthewma7**
Uses a table layout to show some meta of dataset instead of showing the raw JSON

chrome_2017-10-30_09-49-55

### CODE REVIEW

**Comment by aashish24** [comment]
@matthewma7 this looks good. Few suggestions: 

1. Can we remove all the extra whitespace from the right side.. I do not see that space serving any purpose

2. I would suggest that we make the table 100% width and height at bottom half of the dialog

3. Remove the table borders - all of them. I feel that they are distraction? 

I can be convinced otherwise :) these are merely suggestions.

**Comment by matthewma7** [comment]
@aashish24 I can see your suggestion would make it looks better. I will work on that.

**Comment by matthewma7** [comment]
@aashish24, I pushed a commit base on your suggestion, but the table borders are kept but lightened. I no border make the content less focused.

chrome_2017-10-30_09-49-10

**Comment by aashish24** [comment]
thanks @matthewma7 can we resolve the conflict so that I can test again?

**Comment by matthewma7** [comment]
@aashish24 Thanks your review!

**Pull request merged**
