### PR TITLE
S3 source refactor

### PR DESCRIPTION
**Pull request by mgrauer**
This PR converts the client side S3 dataset to an S3 source, and adds support for an S3 source on the backend.

Still some Todos.

### CODE REVIEW

**Comment by mgrauer** [comment]
Todos all done.  This refactors the source panel and dataset panel a bit, hopefully making it easier to add new sources.

I've removed the upload link for Datasets.  We can bring that back once we have some more specific use cases and clean up a lot of the associated client side code.

screen shot 2015-10-20 at 11 09 30 pm

S3 is now displayed as an available source type to add.

screen shot 2015-10-20 at 11 09 52 pm

Ug.  Seeing the repeated word "source" in that screenshot bothers me.  I'll push a fix.

After selecting S3, you can enter the details of the new source.

screen shot 2015-10-20 at 11 11 51 pm

Adding the S3 source will trigger an import job just like before, and will add a new source to the source panel.

screen shot 2015-10-20 at 11 12 11 pm

You can click on the cloud icon in the source panel to get a read only hierarchy view of the S3 data that has been imported.

screen shot 2015-10-20 at 11 12 25 pm

Clicking on the mean contour analysis allows you to select from the available S3 sources, navigate their imported hierarchy, and select an item.  That, plus specifying a parameter as before allows you to start a mean contour analysis job.


screen shot 2015-10-20 at 11 12 51 pm

A mean contour analysis job is created, as before, and the result of the job is a new dataset as before.
screen shot 2015-10-20 at 11 13 09 pm

You can still display the resulting contour json, i.e. I didn't break that.

screen shot 2015-10-20 at 11 13 33 pm

**Comment by mgrauer** [comment]
Ready for review.  @kotfic is probably best to review this.  

It isn't as bad as it seems.  You can follow along with the [documentation changes](https://github.com/Kitware/minerva/pull/159/files#diff-47694ad0b0af0af4d21b9853eb54d9d2) describing how to create a source and look at the screenshot driven narrative in the comment above.

@mbertrand @essamjoubori PTAL if you are curious about the S3/spark/contour analysis pipeline.

**Comment by aashish24** [comment]
> I've removed the upload link for Datasets. We can bring that back once we have some more specific use cases and clean up a lot of the associated client side code.

+1. Can we add a "Local source" option? The idea is that using that source you can load files from your local filesystem. More specific sources such as "Raster" and "Vector", "Gridded" can be added later.

**Comment by mgrauer** [comment]
I think that will work--the harder part will be setting up the right UI to allow specifying the source type.

Do you want to see the Local source as part of this work, or can I add an issue for it?

**Comment by aashish24** [comment]
> Do you want to see the Local source as part of this work, or can I add an issue for it?

Not part of this work. A new issue would be ideal. The use case we have is this:
* Use uploads PDF from her/his filesystem
* We run some analysis on those PDF's that generates tabular data
* We upload that data into MongoDB via Girder

So I am thinking having a "Local" source would be nice here that enables you to load any filetype to our system.

**Comment by mgrauer** [comment]
Issue added.  The local source upload part is easy.  Dealing with arbitrary file types is the hard part.  We could do just a pdf uploader as a first pass (select local source type, then select pdf).

**Comment by aashish24** [comment]
> Issue added. The local source upload part is easy. Dealing with arbitrary file types is the hard part. We could do just a pdf uploader as a first pass (select local source type, then select pdf).

Roger that. Yes, think dealing with arbitrary formats would be hard. I think we may need to work on file type specific readers (one solution).

**Comment by aashish24** [comment]
@kotfic can you review this when you get some time?

**Comment by kotfic** [comment]
Looks like this is not working on girder master,  I am seeing the following 

```json
{field: "bucket", message: "Unable to connect to bucket "nasanex".", type: "validation"}
```

when trying to create a new s3 source through the frontend.

**Comment by mgrauer** [comment]
This is a problem in Girder, see https://github.com/girder/girder/issues/1056.

**Comment by aashish24** [comment]
@kotfic could you please review this soon?

**Comment by kotfic** [comment]
@mgrauer LGTM !

**Pull request merged**
