### PR TITLE
ENH: Add additional colormap scalings.

### PR DESCRIPTION
**Pull request by danlipsa**
Add clamping for linear scaling
Add quantile scaling
Fix log scaling

### CODE REVIEW

**Comment by danlipsa** [comment]
@aashish24 @matthewma7 @dorukozturk Please review.

**Comment by dorukozturk** [comment]
@danlipsa The functionality works great. 
There are 2 things:
1) When clicked on the clamp checkbox first time, the input boxes do not appear.
deepinscreenshot20170512081236

2) We should probably limit the clamp functionality to numeric properties only. 

Other than that LGTM.

**Comment by danlipsa** [comment]
@dorukozturk For 1. Do you need to expand the clamping layout? For 2. I agree, even more we need to limit all scaling (linear, log and quantile) to numeric properties only, not only clamping. I plan to address this next time I work on minerva.

**Comment by dorukozturk** [comment]
@danlipsa if we expand the layout by default that should solve the first problem. The second issue is more important I think. Let me know if you need anything from me.

**Comment by danlipsa** [comment]
@dorukozturk As we discussed, the first problem is a feature of how the panels (Clamping, Fill and Stroke) are implemented, not a bug. :smile: If its checkbox is unchecked, a panel is loaded hidden. Maybe a way to 
make it easier for the user would be to expand the panel when the user checks its checkbox.

I filed an issue for the second problem
https://github.com/Kitware/minerva/issues/406

Ready to merge?

**Pull request merged**
