### PR TITLE
Create a WMS Dataset that can be displayed in Minerva

### PR DESCRIPTION
**Pull request by essamjoubori**
- Have UI control to create a new WMS Source
 - Call GetCapabilities (backend) on WMS source and retrieve list of layers (with/without authentication) 
 - Have UI control to create a new WMS Dataset from the WMS Source
 - Have the WMS Dataset rendered on geojs (currently, only not-authenticated WMS Datasets can be rendered on the map)
 - Retrieve legend (backend), include it in the metadata, and display it on the bottom left corner of the map (currently, only not-authenticated legends can be displayed)

### CODE REVIEW

**Comment by aashish24** [comment]
Nice @essamjoubori :clap:.. ..I will review it after @mgrauer does it.

**Comment by mgrauer** [comment]
@essamjoubori I'll start listing QA comments here, though I won't finish this today.

-  [ ] change the name of the branch from `essam` to something more meaningful; if you are on the head of this branch on your command line, you can do `git checkout -b wms_display` or similar, then you'll have to push it and create a new PR.  Do you have the permissions to push directly to this repo?
-  [ ] there is already a [`.jshintrc`](https://github.com/Kitware/minerva/blob/a34b9abb6561fd07a1a5ecad4411d3dded592752/plugin.cmake#L51) that we merge with the overall Girder one, you can make additions there if need be.  Can you remove the one you added at the top level?
- [ ] remove the three files added under `src`, add `src` to the .gitignore (I should have done this before now :grin:: )

**Comment by essamjoubori** [comment]
@mgrauer I've made the changes and created a new PR with the same title. You may close this one.

I don't believe I have the permissions to push directly to this repo.

Thanks!

**Comment by jbeezley** [comment]
We should get the Epidemico folks permissions on this repo.  Currently all of us Kitware people have access with the Arbor workflows group.  I'm thinking we should create a new group for this purpose.  What do you think @aashish24?

**Comment by aashish24** [comment]
Thanks for bringing this up @jbeezley. I will fix the group and the permissions.

**Comment by aashish24** [comment]
@jbeezley should be all set. I added Matt and others. @essamjoubori let me know if I missed someone.

**Pull request closed without merging**
