### PR TITLE
Added a BSVE CLI to help work with their API

### PR DESCRIPTION
**Pull request by jbeezley**
I decided to cherry pick my other BSVE branch to push in the server side content alone without the client side components, which will take longer to finish.  I still need to fix the analysis test, but I think the actual search functionality still works.

### CODE REVIEW

**Comment by jbeezley** [comment]
Update: fixed the test.  This is ready for review.

**Comment by mgrauer** [comment]
LGTM.  

It might be nice to have the CLI take a path to a JSON file of the credentials or pull from ENV vars, but I won't request these features until I have an actual need.

**Comment by danlamanna** [comment]
No [click](http://click.pocoo.org/5/)? :P

**Comment by jbeezley** [comment]
The CLI does actually use [environment variables](https://github.com/Kitware/minerva/blob/bsve-search-utility/server/utility/bsve/bsve_utility.py#L329-L340): `BSVE_USERNAME`, `BSVE_APIKEY`, `BSVE_SECRETKEY`.  I set those in bashrc so I don't have to worry about it.

**Comment by jbeezley** [comment]
@danlamanna I actually found click after I had done most of this, otherwise I would have considered it.

**Pull request merged**
