### PR TITLE
Remove unused and abandoned code

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Fixes #463 #461

**Comment by aashish24** [comment]
@matthewma7 the WMS portion of code is not clear to me. I think WMS code needs some decent fixing. I am wondering if we should remove the code now and add it back later if we need it. I do not think currently we need it for any active project. thoughts? I or you may have to push more code to remove traces of WMS

**Comment by matthewma7** [comment]
@aashish24 I am not really certain about the WMS code. I would like to ask, @jbeezley, does the WMS imported dataset in BSVE use any of these codes?

**Comment by jbeezley** [comment]
BSVE reference layers derive from WMS layers, but I don't think it relies on this specific code, which is just the "Add a WMS layer" button.

**Comment by aashish24** [comment]
Thanks @jbeezley @matthewma7

**Pull request merged**
