### PR TITLE
Load saved wms in session

### LINKED ISSUE #118: Session with saved WMS layer fails to display when loaded
From this [comment](https://github.com/Kitware/minerva/pull/117#issuecomment-142347494)

### PR DESCRIPTION
**Pull request by mgrauer**
fixes #118.

@mbertrand this is the bug you found.  I'm glad you mentioned it, that part of the code was kinda confusing, I think this is an improvement in clarity.

### CODE REVIEW

**Comment by mgrauer** [comment]
I also had to do a bit of Travis work on this branch.  Note that commit 66aa0a9 and before are all already in master.

**Comment by mgrauer** [comment]
Rebased this PR so that it is much easier to QA.  

To see the problem this commit fixes: on master, create a WMS source, then a dataset layer from that source.  Add the layer to the map, then save the session.  Now refresh the page, and you'll see an error.

**Comment by aashish24** [comment]
@mgrauer can you update this branch?

**Comment by aashish24** [comment]
the changes looks reasonable but I didn't run the code.

**Comment by mgrauer** [comment]
@mbertrand you reported this bug initially, would you mind checking if it fixes your issue?

**Comment by mbertrand** [comment]
@mgrauer it does fix the issue, thanks

**Pull request merged**
