### PR TITLE
[WIP] Add pip install docs

### PR DESCRIPTION
**Pull request by mgrauer**
A draft based on testing the install path prior to Girder 1.4.0 release.  

Should be updated as part of #204.  I didn't want to lose this info before then.

### CODE REVIEW

**Comment by mgrauer** [comment]
Completely unrelated, wms_test failed.  This PR is morphing into housekeeping.

**Comment by mgrauer** [comment]
@danlamanna PTAL

**Comment by aashish24** [comment]
@mgrauer what's holding this branch?

**Comment by aashish24** [comment]
ping @mgrauer

**Comment by mgrauer** [comment]
I'll pull the developer docs out of this and rebuild the PR.

**Comment by aashish24** [comment]
> I'll pull the developer docs out of this and rebuild the PR.

thanks!

**Comment by aashish24** [comment]
@mgrauer is this still valid?

**Comment by mgrauer** [comment]
No longer valid, nor in progress.  Closing.

**Pull request closed without merging**
