### PR TITLE
Rename Dataset feature

### PR DESCRIPTION
**Pull request by matthewma7**

### CODE REVIEW

**Comment by aashish24** [comment]
@matthewma7 I see lot of white-space in the popup in my testing. Is that something we can fix. I think anytime we have have a very large white space, I prefer we fit it nicely so that we do not hide the background.

**Comment by matthewma7** [comment]
@aashish24 I see. I'll update this one's style.

**Comment by matthewma7** [comment]
@aashish24 I updated the style to avoid whitespace. Please take another look.

**Comment by matthewma7** [comment]
@aashish24 Thanks for the reviewing. 👍

**Pull request merged**
