### PR TITLE
Revise mako

### PR DESCRIPTION
**Pull request by mgrauer**
I needed to add in datatables for CSV viewing, so I did some work to address #271 .  Further work could be done to unify the css similarly.

This only works with a relatively recent Girder master, so maybe should wait to go in until v1.4.2, or else I should update the Girder branch in Travis to master.

@jbeezley I didn't touch any of the testing stuff so as to not get in your way.  Let me know if this moves things in the direction you want or if you have specific advice.

### CODE REVIEW

**Comment by jbeezley** [comment]
Thanks for the heads up.  It's unlikely I will get to making any changes that conflicts with what you are doing in this branch anytime soon.

**Comment by aashish24** [comment]
@mgrauer why its WIP? Are you expecting more changes?

**Comment by mgrauer** [comment]
@aashish24 I wanted to gather feedback and also it pushes us onto Girder master (at least as far as Travis is concerned).

My feeling is that it is better for us to got to Girder v1.4.2 once that gets released, and make all of the changes at one time.  I'm happy to hear other opinions on this, such as, perhaps we could move Travis to Girder master for now and then peg to v1.4.2 upon its release.

I'll force push the branch to clean it up at least and then we can discuss further.

**Comment by mgrauer** [comment]
@kotfic  Let me know if this satisfies your needs in #271.

**Comment by mgrauer** [comment]
Talking to @kotfic  and @zachmullen today about integration branches gave me the idea to do that here.

Currently we are pegged to girder v1.4.1 in travis and a few other places.  Some branches, like this one, and #259, should go against the next Girder release, when we  move to that in Minerva.  We could create an integration branch in Minerva (called girder_1_5_0 or something), and then target and merge any PRs into that which need Girder functionality past v1.4.1.  We could set the travis Girder version to "master" in that integration branch, or set it commit by commit as PRs get merged into it.

There will probably be merge conflicts to resolve when we bring the integration branch into master.  Another option is to leave these types of PRs hanging around, and then merge them into master individually when the time is right, but that would likely result in merge conflicts also.

Any strong opinions here?

**Comment by kotfic** [comment]
@mgrauer this looks good for my use case (LGFMUC?) - which initiated #271.  

From a practical perspective I need this change,  and the change in girder, before I can continue work on the cumulus/minerva front-end integration. If there was an integration branch that tracked girder master (until there is a release)  I think that would make that easier.  I just don't want to be in a position where i need a fix that has gone into minerva/master  and not into minerva/girder_1_5_0

So do we merge minerva/master into this integration branch after PR's go into master? rebase with force-lease? Who is responsible for making sure the integration branch is in sync with minerva/master?

**Comment by mgrauer** [comment]
@kotfic 

Here's what I propose:

* I'll create a GH label `girder_1_5_0`
* I'll create a new branch called `girder_1_5_0` that will have a standing PR, and that changes
  * travis to Girder:master
  * ansible to Girder:master
  * specifies somewhere in the docs that it is pinned to girder 1.5.0
* I'll create a new PR for this (#277) branch and for #259 that target the branch `girder_1_5_0`, have the label `girder_1_5_0`, link the new PRs back to the originals, then close this (#277) and #259, and merge these PRs.  As part of creating those new PRs I will probably change those branches a bit to remove the travis/ansible girder version changes.

Then any new PRs that need Girder 1.5.0 would target the `girder_1_5_0` branch and have the label `girder_1_5_0`.

Any new PRs that don't need Girder 1.5 would target Minerva's `master` (the usual flow), and upon merging those PRs into Minerva's `master`, I will merge Minerva's `master` into the `girder_1_5_0` branch.

Hopefully Girder 1.5.0 comes out soon and we can peg the 3 parts of that branch to Girder v1.5.0 and then merge `girder_1_5_0` into Minerva `master`.

How does this sound?

**Comment by mgrauer** [comment]
We have elected to bump the version of girder we peg to.  After #281 gets merged, this branch should be rebased from there and then could go directly in.

**Comment by mgrauer** [comment]
I will rebase this on master, then test locally and with ansible.

**Comment by mgrauer** [comment]
@kotfic @danlamanna 

This works for me, travis, and ansible.

PTAL.

**Comment by mgrauer** [comment]
Live by the LGFMUC, die by the LGFMUC.  Merging.

**Comment by kotfic** [comment]
@mgrauer 
powers

**Pull request merged**
