### PR TITLE
Add source panel

### PR DESCRIPTION
**Pull request by mgrauer**
Based on #115.  Will need to be rebased once that goes into master.

### CODE REVIEW

**Comment by mgrauer** [comment]
Fixes #113.  Fixes #95.

Still an issue with WMS layers being added multiple times.  Add them from a source, delete them.  Add them again, 2 are added, delete them.  Add them again, 3 are added.  etc.

Removing the line
  
    this.$el.children().detach();

may have been premature, but putting it back in doesn't seem to fix the issue.  I'll look into it further tomorrow.  

@essamjoubori, let me know if you have a fix for this.

**Comment by essamjoubori** [comment]
@mgrauer I faced this issue before. I believe this is what's happening: the `showWmsLayersList` function (in views/DataPanel) is called every time you show the list of layers from the source and that will create multiple `WmsLayersListWidget` views and duplicated events.
I solved this issue before by adding this conditional statement: https://github.com/Kitware/minerva/blob/wms_display/web_external/js/views/body/DataPanel.js#L143-Lundefined
I wasn't able to reproduce the bug. Let me know if you still having this issue.

**Comment by mgrauer** [comment]
Thanks for the clue @essamjoubori .  I changed that code you referred to because of a bug, but my change introduced a new bug.  At this point they are both fixed.

The only problem I see left on this branch is an error where you have a WMS Layer Dataset, you add it to the map and then remove it from the map, and then try to delete the dataset, you get an error message from GeoJs saying

>Uncaught TypeError: Cannot read property '_exit' of null

I found a fix for this while investigating and will push shortly.

**Comment by mgrauer** [comment]
Rebased on current master now that #115 is merged.  

Ready for review @essamjoubori @mbertrand

**Comment by mbertrand** [comment]
@mgrauer, @essamjoubori  I tried it out, looks good.  I'm experiencing an issue though when trying to re-open a saved session:  I get a mostly blank page under the header with a javascript exception being "Uncaught TypeError: Cannot read property 'createLayer' of undefined" in MapPanel.js (https://github.com/Kitware/minerva/blob/master/web_external/js/views/body/MapPanel.js#L59).  But this happens for me on the master branch too.

**Comment by mgrauer** [comment]
Thanks for the report @mbertrand .  I'd like to fix that in a separate PR, as this one is long enough as is, and as you say, this also exists on master.

**Comment by mgrauer** [comment]
I'm going to merge this based on @mbertrand 's LG.

**Pull request merged**
