### PR TITLE
Downgrade romanesco on travis for girder compatibility

### PR DESCRIPTION
**Pull request by jbeezley**
This will (hopefully) fix the failing client test.

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley does this SHA works with girder master as of today?

**Comment by jbeezley** [comment]
Probably, but I'm not sure.  The point is that it *does* work with the version on girder we install on Travis.  I could have updated girder but there is a much greater chance that would break something else in the process.

**Comment by aashish24** [comment]
> could have updated girder but there is a much greater chance that would break something else in the process.

Sounds reasonable. Thanks,

**Comment by mgrauer** [comment]
@jbeezley This looks fine, thanks for fixing, but I don't understand your comment.  Can you provide more context?

    # after this, need to update girder

**Comment by jbeezley** [comment]
If we update romanesco passed that SHA, we need to update girder as well.

**Comment by mgrauer** [comment]
Thanks @jbeezley, I added that clarification to the branch.  I was reading it "after this" as something I needed to do further down in the Travis file.

LGTM.

**Comment by jbeezley** [comment]
Ah yes, that's much better.

**Pull request merged**
