### PR TITLE
Use geojs from github

### PR DESCRIPTION
**Pull request by jbeezley**
As of https://github.com/OpenGeoscience/geojs/pull/460, you can npm install geojs directly from github.

### CODE REVIEW

**Comment by mgrauer** [comment]
@jbeezley In Minerva's gruntfile, we [build geo.ext.min.js](https://github.com/Kitware/minerva/blob/b1b6bd0eb81786066b27df2b0233f8bc161e4f90/Gruntfile.js#L113-L115) out of a subset of those components built into GeoJs' provided geo.ext.min.js.  Will this still work when taking geojs from github?

**Comment by jbeezley** [comment]
Yes.  This essentially does what the documentation I took out said.  It clones geojs into `node_modules` and then builds it, but it happens automatically.

I'm currently having issues the build to work on travis.  I'll let you know when I have it worked out.

**Comment by jbeezley** [comment]
@mgrauer A manual build step for geojs will be necessary for the time being.  This is for roughly the same reason you have to do `npm install` in minerva before doing it in girder.  Adding the geojs build step to the main grunt build isn't fantastic, but it makes it so there aren't as many manual steps necessary to install.

Also, this build fails due to a pymongo update in girder master.

**Comment by jbeezley** [comment]
I fixed the pymongo error.  The remaining failures are the usual suspects:

```
The following tests FAILED:
	121 - server_minerva.s3_dataset (Failed)
	123 - server_minerva.contour_analysis (Failed)
	127 - server_minerva.mean_contour_analysis (Failed)
```

**Comment by mgrauer** [comment]
@jbeezley where/how did you fix the pymongo issue? @mbertrand is going to start working on a mongo source in minerva and I want him to know anything relevant.

**Comment by jbeezley** [comment]
I just had to update pymongo in romanesco.

**Comment by mgrauer** [comment]
@jbeezley All three tests are failing with "message": "Unable to connect to S3 assetstore", which is due to https://github.com/girder/girder/issues/1056.  

I give your commits here a LGTM.  I say we go ahead and merge this with the failing tests.  Are you good with that?

**Comment by aashish24** [comment]
@jbeezley I am going to merge this one as I am trying to change something and could use this branch.

**Pull request merged**
