### PR TITLE
[TIRFMPBIWTTADITPRWI] Add Minerva logo with owl image

### PR DESCRIPTION
**Pull request by mgrauer**
I got sick of our ugly header.

Old header

screen shot 2015-11-23 at 2 36 47 pm

Proposed in this PR

screen shot 2015-11-23 at 2 37 09 pm

### CODE REVIEW

**Comment by aashish24** [comment]
@mgrauer coming up with a logo is always fun :smile:  I am fine with this logo but let's have a general discussion and may be steve can create few logo samples for us.

**Comment by aashish24** [comment]
@mgrauer few things:  I am assuming that there is no copyright issue with the image? Also, for now, should we add the logo in README as well?

**Comment by mgrauer** [comment]
Weird that mean_contour_analysis is consistently failing on the PR build but succeeding on the push build.  And this commit is rebased on master, so those two should really be the same.

**Comment by mgrauer** [comment]
@aashish24 

As attached as I am to the owl "lefty", this PR is for gathering feedback.

We can use the image, it is CC0 Public Domain with no attribution required.  

See https://pixabay.com/en/owl-bird-black-and-white-wildlife-29673/.

If we do have this as our logo, it would make sense to add it to the Readme, and Readthedocs.

**Comment by aashish24** [comment]
thanks @mgrauer looks like we should be fine. They said that link back to them is appreciated but   not required. 

```
Uploaded Images and Videos on Pixabay are released under Creative Commons CC0. To the extent possible under law, uploaders of Pixabay have waived their copyright and related or neighboring rights to these Images and Videos. You are free to adapt and use them for commercial purposes without attributing the original author or source. Although not required, a link back to Pixabay is appreciated.
```

> If we do have this as our logo, it would make sense to add it to the Readme, and Readthedocs.

Lets ping Steve to see if he create some samples for us. If in the meantime, if you want to treat this as a interim logo, I am good with that. Its a cool image :+1:

**Comment by aashish24** [comment]
@mgrauer thinking some more on this. Would it be okay if we discuss this further before we merge this branch?

**Comment by mgrauer** [comment]
That's what I was hoping for with this PR.  I changed it WIP.  Really I want a different status for the PR, like "this is ready from my perspective but I want to trigger a discussion in the PR with it".

**Comment by aashish24** [comment]
> "this is ready from my perspective but I want to trigger a discussion in the PR with it

+1, thanks, I think WIP sounds reasonable to me. Not sure if folks have other conventions

**Comment by jbeezley** [comment]
TIRFMPBIWTTADITPRWI

**Comment by mgrauer** [comment]
I've add the owl to the readme and rebased.  I'm going to leave readthedocs alone for now.

This branch is ready to be discussed.  My opinion is that it improves the look of Minerva and should be merged even if only on an interim basis.

**Comment by aashish24** [comment]
> This branch is ready to be discussed. My opinion is that it improves the look of Minerva and should be merged even if only on an interim basis.

@mgrauer I am thinking to hold off on this. Let's work with Steve on creating some logo design and then use that in this branch. It won't take Steve very long to create Resonant consistent logo (voting how-ever may take longer).

**Comment by mgrauer** [comment]
SCREEEEEEEEECH!!!

ok, closing this PR.  I added an issue to create a logo.

**Comment by aashish24** [comment]
thanks and sorry :disappointed:

**Pull request closed without merging**
