### PR TITLE
Fix MMWR import for new BSVE data scheme

### PR DESCRIPTION
**Pull request by jbeezley**
@mgrauer This should fix the issue we encountered today.

### CODE REVIEW

**Comment by aashish24** [comment]
This is quick! Nice @jbeezley

**Comment by mgrauer** [comment]
I'll QA now.  Looks like there was a pep8 failure.  I can fix unless you have already done so @jbeezley ?

**Comment by jbeezley** [comment]
Have at it.  My concentration moved on to other things.

**Comment by mgrauer** [comment]
LGTM.  Thanks for the fix.  Merging.

**Pull request merged**
