### PR TITLE
[WIP] Minerva session tests

### PR DESCRIPTION
**Pull request by kotfic**
This is not ready to commit yet,  still having some trouble with getting session metadata to upload correctly to the server via phantomJS

### CODE REVIEW

**Comment by kotfic** [comment]
Note:  this will resolve https://github.com/Kitware/minerva/issues/70  once merged in,  see: 79d6240

**Comment by aashish24** [comment]
@kotfic is this branch relevant anymore?

**Comment by mgrauer** [comment]
@aashish24 

This branch is relevant, it is also a good shame inducer, reminding us that we need to add client side testing.  There are some pieces here that we can use.

**Comment by kotfic** [comment]
@aashish24 I agree with @mgrauer though it obviously need to be rebased against master.

**Comment by aashish24** [comment]
Sounds good @kotfic @mgrauer

**Comment by aashish24** [comment]
Ping @kotfic? If its not too much work, can we either finish this branch or close the pull request?

**Comment by mgrauer** [comment]
I'm going to close it.  I've captured the need for client+server tests in #202.

I had previously pulled out @kotfic 's fix from 79d6240, it was merged into master in b6a4025.

**Pull request closed without merging**
