### PR TITLE
Minerva without romanesco

### PR DESCRIPTION
**Pull request by dorukozturk**
This PR decouples Romanesco from Minerva.

### CODE REVIEW

**Comment by aashish24** [comment]
Congrats on your very first PR :tada:

**Comment by aashish24** [comment]
This branch seems very close. I just did git grep romanesco and found few other places (in documentation and in ansible) that we could clean up as well. I am fine with taking care of ansible in other branch.

**Comment by kotfic** [comment]
@dorukozturk All "spark" related code will also need to be removed as this exclusively depended on the mean_contour analysis.  Please also remove all analyses in the analyses/ folder as these are romanesco analyses.    Please also take a look at the .travis.yml and make sure no romanesco/spark related things are being installed for continuous integration tests.

Thanks!

**Comment by dorukozturk** [comment]
@aashish24 Thank you very much. I did not want to play with the ansible scripts not to break it. 
@kotfic That will be my next task.

**Comment by aashish24** [comment]
@dorukozturk thanks for removing other pieces as well. I will have a look at it today.

**Comment by aashish24** [comment]
@dorukozturk I didn't try the ansible / vagrant, other changes :+1:

**Comment by aashish24** [comment]
LGTM :+1:

**Pull request merged**
